import 'dart:math' as math;

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:just_bored/configs/constants.dart';

import '../../../../configs/debug_fns.dart';

/// controls & manages home screen
class HomeController with ChangeNotifier {
  /// controls & manages home screen
  HomeController();

  /// array of short tagline, generated by the ChatGPT model
  final _tagLines = [
    'The practice of mindfulness and meditation brings calmness and peace to the soul.',
    'Disconnecting from technology is the key to unlocking good mental health and peace of mind.',
    'The act of journaling can be a transformative tool for calming the mind and reflecting on thoughts.',
    'A positive environment is essential to promote good mental health and a peaceful state of mind.',
    '"We do not learn from experience, we learn from reflecting on experience." - John Dewey',
    '"Self-reflection is the school of wisdom." - Baltasar Gracian',
    '"Knowing yourself is the beginning of all wisdom." - Aristotle',
    '"The most important relationship you will ever have is the one with yourself." - Diane Von Furstenberg',
    'Setting boundaries and learning to say no are critical steps in reducing stress and achieving inner calm.',
    'Love is patient, kind, and always forgiving.',
    'Love isn\'t about finding someone perfect, it\'s about loving someone imperfectly.',
    'Love is not just romantic, it\'s also friendship, family, and community.',
    'Love is universal and knows no boundaries.',
    'Take care of your mind, it\'s the most important thing you\'ll ever own.',
    'A clear mind and a peaceful heart can overcome any obstacle.',
    'When you prioritize your mental health, everything else falls into place.',
    'Meditation is not an escape from reality, but a way to connect with it on a deeper level.',
    'Take a deep breath and let go of what no longer serves you.',
    'The power to find peace and calmness lies within you, so trust yourself.',
    'A peaceful mind is the foundation of a happy life.',
    'When you choose to focus on the positive, you create a more peaceful world.',
    'The journey to good mental health is a marathon, not a sprint. Pace yourself and enjoy the scenery.',
    'Love is the most powerful force in the world.',
    'Love is not just a feeling, it\'s a choice you make every day.',
    '"The unexamined life is not worth living." - Socrates',
    'Investing in self-care activities is a powerful way to promote good mental health and a peaceful state of mind.',
    'Exercise is not only great for the body, but also an effective way to reduce stress and promote mental wellbeing.',
    'Gratitude is the secret ingredient to inner peace and long-lasting happiness.',
    'Getting enough sleep is the foundation of good mental health and the key to unlocking a peaceful state of mind.',
    'Living in the present moment is the key to unlocking inner calm and reducing anxiety.',
    'Peace and calmness come from within, so take the time to nurture your mental health.',
    'The path to good mental health is paved with self-care and self-compassion.',
    '"True self-discovery begins where your comfort zone ends." - Adam Braun',
    '"Self-reflection is a humbling process. It\'s essential to find out why you think, say, and do certain things...then better yourself." - Sonya Teclai',
    '"Self-reflection is a mirror in which we can see beyond the surface of our thoughts and feelings." - Amit Ray',
    '"You have to do your own growing no matter how tall your grandfather was." - Abraham Lincoln'
  ];

  //Firebase realtime database instance
  FirebaseDatabase database = FirebaseDatabase.instance;

  String _tagLine = '';
  String get tagLine => _tagLine;

  /// fetch random taglines
  void fetchRandomTagLines() {
    // get a random number from 0 to length of array
    int number = math.Random().nextInt(_tagLines.length);
    _tagLine = _tagLines[number];
  }

  String _selectedMood = '';

  /// user selected mood
  String get selectedMood => _selectedMood;

  /// for mood change
  ///
  /// if the user selects an already selected mood, it clears away
  ///
  /// else it sets that selected mood as the current mood
  Future<void> selectMood(String mood) async {
    if (_selectedMood == mood) {
      _selectedMood = 'none';
    } else {
      _selectedMood = mood;
    }
    printOut('Update Mood = $_selectedMood', 'Home Controller');

    String? uid = FirebaseAuth.instance.currentUser?.uid;
    printOut('UID = $uid', 'HomeController');

    if (uid == null) {
      showToast('User updating mood cannot be empty');
      return;
    }

    // get timestamp
    //final timestamp = DateTime.now();

    //final data = {'mood': mood, 'time': timestamp.toString()};

    //await database.refFromURL('users/$uid').set(data);

    // // perform firestore storage --aOnYZEX0fXgJD1QqLpmpe8rF6wH2
    // final moodLog = FirebaseFirestore.instance.collection('mood_logs').doc(uid);

    // // get timestamp
    // final timestamp = DateTime.now();

    // final data = {'mood': mood, 'time': timestamp};

    // await moodLog.set(data).then((_) => showToast('Mood updated'));

    notifyListeners();
  }

  /// sets user reflection
  /// This will be allowed only twice a day, morning hours at 10am and evening hours at 8pm
  void setUserReflection({
    required BuildContext context,
    required GlobalKey<FormState> formKey,
    required Map<String, String> userReflection,
  }) {
    final isValid = formKey.currentState!.validate();
    if (isValid) {
      formKey.currentState!.save();
      printOut(userReflection, 'Reflection');
    }
  }

  /// reset all [HomeController] variable
  void reset() {
    _selectedMood = '';
    _tagLine = '';
  }
}
